---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - distri-infer.ndsl.cn
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - distri-infer.ndsl.cn
  resources:
  - pipelines/finalizers
  verbs:
  - update
- apiGroups:
  - distri-infer.ndsl.cn
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
